### ISSUE TITLE
cookie and gevent supported

### ISSUE THREAD

**Issue by shscy** [gaojiuli/xweb#6]
cookie and session is  necessary function. wsgi protocol is sync. you can not  take advantage of the asyncio in python >= 3.4. so you have to supporte gevent.

**Comment by elliotgao2** [comment]
## session
Most of the time, session is not used, because our api should support both mobile client and web client , which methods of authentication is usually Oauth2 or token that need not session. 

So i don't think this is a necessary function, Is there any another reason ?

## gevent

Xweb meets the standard of wsgi. So the xweb has the some way of deployment as flask.
